### ISSUE TITLE
repo doesn't have any code

### ISSUE THREAD

**Issue by m0wer** [omkarcloud/google-maps-reviews-scraper#1]
Is it intended?

**Comment by Chetan11-dev** [comment]
There are two repositories: 'omkarcloud/google-maps-reviews-scraper' and 'omkarcloud/google-maps-scraper'.

Both repositories use the same web scraper (omkarcloud/google-maps-scraper) but are tailored for different audiences:

**omkarcloud/google-maps-reviews-scraper:** 
- Designed for Data Scientists.
- Its README focuses on scraping reviews for sentiment analysis.

**omkarcloud/google-maps-scraper:** 
- Aimed at Entrepreneurs.
- Its README focuses on extracting business listings.

As for the Code, Kindly find the complete code at [omkarcloud/google-maps-scraper](https://github.com/omkarcloud/google-maps-scraper)

**Comment by m0wer** [comment]
Thanks!
